name: user_repository
description: Dart package to manage the user domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter