name: sensazion_app
description: "Muévete con información, sin miedo"
publish_to: 'none'
platforms:
  android:
  ios:
version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.9.0
  equatable: ^2.0.7
  formz: ^0.8.0
  
  user_repository:
    path: packages/user_repository
  authentication_repository:
    path: packages/authentication_repository
  core:
    path: packages/core
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_lint: ^0.2.0-dev.3
  test: ^1.25.15

flutter:
  uses-material-design: true
  assets:
    - .env