name: core
description: Dart package to manage multiple utilities and shared code.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  test: ^1.25.15
